config/routes.rb
Pong::Application.routes.draw do
  resources :matches do
    collection do
      get 'rankings'
      get 'players'
    end
  end
  root to: 'matches#rankings'
end

app/models/match.rb
class Match < ActiveRecord::Base
  validates :winner,      presence: true
  validates :loser,       presence: true

  belongs_to :winner, :class_name => 'Player'
  belongs_to :loser, :class_name => 'Player'

  before_validation :set_default_occured_at_date, on: :create, :unless => ->{ occured_at.present? }

  private

  def set_default_occured_at_date
    self.occured_at = Time.now
  end
end

app/models/match_point.rb
class MatchPoint
  POINT_CHART = {
    (0..12) => { expected: 8, upset: 8 },
    (13..37) => { expected: 7, upset: 10 },
    (38..62) => { expected: 6, upset: 13 },
    (63..87) => { expected: 5, upset: 16 },
    (88..112) => { expected: 4, upset: 20 },
    (113..137) => { expected: 3, upset: 25 },
    (138..162) => { expected: 2, upset: 30 },
    (163..187) => { expected: 2, upset: 35 },
    (188..212) => { expected: 1, upset: 40 },
    (213..237) => { expected: 1, upset: 45 },
    (238..1500) => { expected: 0, upset: 50 }
  }

  class << self
    def rankings
      players_points = Hash.new(0)

      Match.find_each { |match|
        winner_points, loser_points = players_points.values_at match.winner_id, match.loser_id

        spread = (winner_points - loser_points).abs
        result = winner_points > loser_points ? :expected : :upset
        points_exchange = points_exchanged spread, result

        players_points[match.winner_id] += points_exchange
      }

      players_points.to_a.map { |player_id, points| [Player.find(player_id), points] }.sort_by { |_,pts| pts }.reverse
    end

    def points_exchanged spread, result
      @ratings ||= POINT_CHART.inject({}) { |acc, (k,v)|
        [*k].map { |i| acc[i] = v }
        acc
      }

      @ratings[spread][result]
    end
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  before_validation :downcase_name, :if => ->{ name.present? }

  validates :name, presence: true, uniqueness: true

  def display_name
    name.split("'").map(&:titleize).join("'")
  end

  private

  def downcase_name
    self.name = self.name.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create

  def create
    winner, loser = params.values_at(:winner_name, :loser_name).map { |name|
      Player.find_or_create_by_name name.strip.downcase
    }

    match = Match.new winner: winner, loser: loser

    unless [winner, loser].all?(&:valid?) && match.save
      flash.alert = "Must specify a winner and a loser to post a match."
    end

    redirect_to matches_path
  end

  def destroy
    Match.find(params[:id]).destroy
    redirect_to matches_path
  end

  def index
    @match = Match.new
    @matches = Match.order("occured_at desc")
  end

  def rankings
    @rankings = MatchPoint.rankings
  end

  def players
    if params[:q]
      query = params[:q].downcase + '%'
      names = Player.where(["LOWER(name) LIKE ?", query]).collect(&:name)
    else
      names = Player.all.collect(&:name)
    end

    render text: names.collect(&:downcase).sort.uniq.collect(&:titleize).join("\n")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_with_current(name, url)
    options = (current_page? url) ? { class: "current" } : {}
    link_to name, url, options
  end

  def location
    ENV["PIVOT_PONG_LOCATION"] || "NYC"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pivot Pong #{location} — #{yield :title}
    = stylesheet_link_tag 'reset', 'pong', 'jquery.autocomplete'
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery.autocomplete', 'jquery.tabs'
    = javascript_include_tag "http://use.typekit.com/rol0dzy.js"
    = javascript_tag "try{Typekit.load();}catch(e){}"
    = favicon_link_tag
    = csrf_meta_tag

  %body
    #page
      %header
        %h1 pivot pong #{location.downcase}
        %nav
          = link_to_with_current "Rankings", root_path
          = link_to_with_current "Matches", matches_path

      = render 'shared/flash_messages'
      = yield
      %footer
        = link_to "source code", "https://github.com/seanmoon/pivot-pong"

app/views/matches/index.html.haml
- content_for :title, "Matches"

= form_for(@match) do |f|
  = label_tag :winner_name
  = text_field_tag :winner_name, "", autocomplete: "off"
  = label_tag :loser_name
  = text_field_tag :loser_name, "", autocomplete: "off"
  = f.label :occured_at
  = f.text_field :occured_at, value: Time.now.strftime("%Y-%m-%d %H:%M:%S")
  = submit_tag "Add match"

%h2 Match history

%table
  %tr
    %th.date Date
    %th Winner
    %th Loser
    %th.action
  - @matches.each do |m|
    %tr{class: cycle("even", "odd")}
      %td.date= m.occured_at.strftime("%Y-%m-%d")
      %td= m.winner.display_name
      %td= m.loser.display_name
      %td.action= link_to "delete", match_path(m), method: :delete

app/views/matches/rankings.html.haml
- content_for :title, "Rankings"

%ol#all-time.rankings
  - @rankings.each do |player, points|
    %li{class: cycle("even", "odd")}
      = "#{player.display_name}"
      %span= "#{points} pts"

app/views/shared/_flash_messages.html.haml
- if notice || alert
  .flash
    - if notice
      .notice= notice
    - if alert
      .alert= alert